version: "3.9"

services:

  jms-app:
    build: .
    container_name: jms-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: jms
      NODE_ENV: production
    volumes:
      - appdata:/app/uploads

  postgres:
    image: postgres:15-alpine
    container_name: jms-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jms
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  appdata:
